language: python
sudo: false
branches:
  only:
    - master
python:
  - "3.5"
  - "3.6"
  
install:
  - pip install --upgrade setuptools
  - pip install -r requirements_travis.txt

script: 
  - py.test thor --cov=thor

after_success:
  - coveralls
